In [35]:
import pandas as pd

In [ ]:
! pip install kaggle

In [ ]:
! mkdir ~/.kaggle

In [4]:
! cp kaggle.json ~/.kaggle/

In [5]:
! chmod 600 ~/.kaggle/kaggle.json

In [ ]:
! kaggle competitions download Fake-News

In [ ]:
! unzip train.csv.zip

In [36]:
df = pd.read_csv('train.csv')

In [37]:
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [38]:
# Drop nan 
df = df.dropna()

In [39]:
# independent and dependent features
X = df.drop('label',axis=1)
y = df['label']

In [40]:
X.shape

(18285, 4)

In [41]:
y.shape

(18285,)

In [42]:
import tensorflow as tf

In [43]:
from tensorflow.keras.layers import Embedding         # for word embedding
# for making all vectors of same length (pre or post padding: include 0 in front or end)
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import  LSTM
from tensorflow.keras.layers import Dense

In [44]:
# Vocabulary Size
voc_size = 8000

# One-Hot Representation

In [45]:
message = X.copy()

In [46]:
message.reset_index(inplace = True)  # since we have dropped nan values

In [47]:
import nltk
import re
from nltk.corpus import stopwords

In [48]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [49]:
## Data Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(message)):
    print(i)
    # substituting everything except a-z and A-Z with '(space)' in message[title]
    review = re.sub('[^a-zA-Z]', ' ', message['title'][i])
    review = review.lower()
    review = review.split()  # applied to remove Stopwords(not necessary words)
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [50]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [51]:
onehot_rep = [one_hot(words, voc_size)for words in corpus]
onehot_rep

[[7366, 5451, 3811, 5987, 254, 3491, 1376, 403, 1425, 7466],
 [1777, 2327, 5942, 3601, 733, 4225, 7069],
 [6794, 4384, 7727, 5629],
 [4849, 791, 880, 6370, 1979, 7697],
 [2490, 733, 5479, 2030, 2479, 2215, 733, 7253, 903, 5799],
 [5378,
  533,
  206,
  5191,
  7497,
  5453,
  176,
  54,
  6723,
  5605,
  2278,
  7521,
  6767,
  4905,
  7069],
 [4448, 7319, 1564, 1779, 7353, 2141, 7147, 944, 940, 4489, 7041],
 [5566, 416, 4090, 4976, 5111, 7996, 5453, 3688, 940, 4489, 7041],
 [6828, 7729, 7209, 7243, 7158, 5522, 3642, 6248, 5453, 3454],
 [7745, 4550, 7617, 1852, 3581, 1706, 1945, 9],
 [6127, 3762, 7611, 4474, 223, 438, 4480, 4160, 6157, 5743, 574],
 [6370, 4687, 254, 5522, 5453, 5111],
 [7427, 972, 2121, 6020, 2739, 5469, 7347, 7779, 425],
 [7943, 4635, 7740, 1682, 2081, 5751, 5059, 940, 4489, 7041],
 [6814, 6169, 2067, 7695, 6086, 940, 4489, 7041],
 [4489, 5969, 5175, 3326, 6640, 6897, 1007, 1352, 2965, 4010],
 [4772, 942, 2327],
 [807, 5593, 793, 7303, 5453, 7800, 3978, 7069],
 [7271,

# Embedding Representation

In [52]:
sen_len = 20
embedded_doc = pad_sequences(onehot_rep, padding='post', maxlen=sen_len)
print(embedded_doc)

[[7366 5451 3811 ...    0    0    0]
 [1777 2327 5942 ...    0    0    0]
 [6794 4384 7727 ...    0    0    0]
 ...
 [4940 6231 3937 ...    0    0    0]
 [4441 5111 1423 ...    0    0    0]
 [4224 1854 4814 ...    0    0    0]]


In [53]:
len(embedded_doc)

18285

# Creating Model

In [54]:
embed_vector_features = 50
model=Sequential()
model.add(Embedding(voc_size, embed_vector_features, input_length=sen_len))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 20, 50)            400000    
_________________________________________________________________
lstm_2 (LSTM)                (None, 100)               60400     
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 101       
Total params: 460,501
Trainable params: 460,501
Non-trainable params: 0
_________________________________________________________________
None


In [55]:
import numpy as np
X_final = np.array(embedded_doc)
y_final = np.array(y)

In [56]:
X_final.shape, y_final.shape

((18285, 20), (18285,))

In [57]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

# Model Training

In [58]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=12, batch_size=64)

Epoch 1/12
192/192 [==============================] - 4s 12ms/step - loss: 0.3094 - accuracy: 0.8503 - val_loss: 0.1984 - val_accuracy: 0.9167
Epoch 2/12
192/192 [==============================] - 2s 11ms/step - loss: 0.1266 - accuracy: 0.9519 - val_loss: 0.1992 - val_accuracy: 0.9200
Epoch 3/12
192/192 [==============================] - 2s 10ms/step - loss: 0.0743 - accuracy: 0.9741 - val_loss: 0.2571 - val_accuracy: 0.9173
Epoch 4/12
192/192 [==============================] - 2s 10ms/step - loss: 0.0479 - accuracy: 0.9835 - val_loss: 0.2749 - val_accuracy: 0.9163
Epoch 5/12
192/192 [==============================] - 2s 10ms/step - loss: 0.0294 - accuracy: 0.9908 - val_loss: 0.3232 - val_accuracy: 0.9109
Epoch 6/12
192/192 [==============================] - 2s 10ms/step - loss: 0.0213 - accuracy: 0.9932 - val_loss: 0.4053 - val_accuracy: 0.9082
Epoch 7/12
192/192 [==============================] - 2s 10ms/step - loss: 0.0174 - accuracy: 0.9936 - val_loss: 0.4884 - val_accuracy: 0.9064

# Adding Dropout

In [59]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sen_len))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

# Performance matrix and accuracy

In [ ]:
y_pred=model.predict_classes(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)